"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { CheckCircle2, FileAudio, ImageIcon, Mic, Pause, Play, RefreshCw, Square, Trash2, Upload, Video, XCircle } from "lucide-react";
import { uploadAudio, uploadImage, uploadVideo, type UploadOptions } from "@/services/upload.service";
import type { IssueMedia } from "@/services";

type Kind = "image" | "video" | "audio";
type Status = "queued" | "uploading" | "success" | "error" | "cancelled";
type Item = { id: string; kind: Kind; file: File; previewUrl?: string; status: Status; progress: number; error?: string; uploaded?: IssueMedia; controller?: AbortController };
export type MediaUploadValue = { imageIds: string[]; videoId?: string; audioId?: string; mediaIds: string[]; files: File[]; isUploading: boolean; hasErrors: boolean };
type ToastType = "success" | "error" | "info";
const MB = 1024 * 1024;
const IMAGE_MAX = 10 * MB;
const VIDEO_MAX = 5 * MB;
const AUDIO_MAX = 10 * MB;
const IMAGE_FORMATS = ["jpg", "jpeg", "png", "webp", "heic"];
const VIDEO_FORMATS = ["mp4", "mov", "webm", "mkv"];
const AUDIO_FORMATS = ["mp3", "wav", "m4a", "ogg", "aac", "webm"];
const emptyValue: MediaUploadValue = { imageIds: [], mediaIds: [], files: [], isUploading: false, hasErrors: false };
function id() { return `${Date.now()}-${Math.random().toString(36).slice(2)}`; }
function ext(file: File) { return file.name.split(".").pop()?.toLowerCase() || ""; }
function size(bytes: number) { return bytes < MB ? `${Math.max(1, Math.round(bytes / 1024))} KB` : `${(bytes / MB).toFixed(2)} MB`; }
function uploadId(media?: IssueMedia) { return media?.id || media?.url || media?.fileName || ""; }
function validate(file: File, formats: string[], max: number, label: string) { if (!formats.includes(ext(file))) throw new Error(`Unsupported ${label} format.`); if (file.size > max) throw new Error(`${label[0].toUpperCase() + label.slice(1)} exceeds ${max / MB} MB.`); }

export function MediaUploadManager({ onChange, onToast }: { onChange: (value: MediaUploadValue) => void; onToast?: (message: string, type?: ToastType) => void }) {
  const [images, setImages] = useState<Item[]>([]);
  const [video, setVideo] = useState<Item | undefined>();
  const [audio, setAudio] = useState<Item | undefined>();
  const [recording, setRecording] = useState<"idle" | "recording" | "paused">("idle");
  const [seconds, setSeconds] = useState(0);
  const imageRef = useRef<HTMLInputElement>(null); const imageReplaceRef = useRef<HTMLInputElement>(null); const imageReplaceId = useRef<string | null>(null); const videoRef = useRef<HTMLInputElement>(null); const audioRef = useRef<HTMLInputElement>(null);
  const recorder = useRef<MediaRecorder | null>(null); const stream = useRef<MediaStream | null>(null); const chunks = useRef<Blob[]>([]); const timer = useRef<number | null>(null);
  const all = useMemo(() => [...images, ...(video ? [video] : []), ...(audio ? [audio] : [])], [images, video, audio]);
  useEffect(() => { const imageIds = images.filter(i => i.status === "success").map(i => uploadId(i.uploaded)).filter(Boolean); const videoId = video?.status === "success" ? uploadId(video.uploaded) : undefined; const audioId = audio?.status === "success" ? uploadId(audio.uploaded) : undefined; onChange({ imageIds, videoId, audioId, mediaIds: [...imageIds, ...(videoId ? [videoId] : []), ...(audioId ? [audioId] : [])], files: all.map(i => i.file), isUploading: all.some(i => i.status === "uploading"), hasErrors: all.some(i => i.status === "error" || i.status === "cancelled") }); }, [all, images, video, audio, onChange]);
  useEffect(() => () => { all.forEach(i => i.previewUrl && URL.revokeObjectURL(i.previewUrl)); stopStream(); }, []);
  function toast(message: string, type: ToastType = "info") { onToast?.(message, type); }
  function setImage(id: string, patch: Partial<Item>) { setImages(cur => cur.map(i => i.id === id ? { ...i, ...patch } : i)); }
  async function start(item: Item, fn: (file: File, options: UploadOptions) => Promise<IssueMedia>, update: (patch: Partial<Item>) => void) { const controller = new AbortController(); update({ status: "uploading", progress: 0, error: undefined, controller }); try { const uploaded = await fn(item.file, { signal: controller.signal, onProgress: progress => update({ progress }) }); update({ status: "success", progress: 100, uploaded, controller: undefined }); toast(`${item.file.name} uploaded`, "success"); } catch (e) { const cancelled = controller.signal.aborted; update({ status: cancelled ? "cancelled" : "error", error: e instanceof Error ? e.message : "Upload Failed", controller: undefined }); toast(cancelled ? "Upload cancelled" : e instanceof Error ? e.message : "Upload Failed", "error"); } }
  function addImages(files: FileList | File[]) { Array.from(files).forEach(file => { try { validate(file, IMAGE_FORMATS, IMAGE_MAX, "image"); const item: Item = { id: id(), kind: "image", file, previewUrl: URL.createObjectURL(file), status: "queued", progress: 0 }; setImages(cur => [...cur, item]); start(item, uploadImage, p => setImage(item.id, p)); } catch (e) { toast(e instanceof Error ? e.message : "Image validation failed", "error"); } }); }
  function replaceImage(files: FileList | null) { const file = files?.[0]; const target = imageReplaceId.current; if (!file || !target) return; const old = images.find(i => i.id === target); old?.controller?.abort(); if (old?.previewUrl) URL.revokeObjectURL(old.previewUrl); try { validate(file, IMAGE_FORMATS, IMAGE_MAX, "image"); const item: Item = { id: target, kind: "image", file, previewUrl: URL.createObjectURL(file), status: "queued", progress: 0 }; setImage(target, item); start(item, uploadImage, p => setImage(target, p)); } catch (e) { setImage(target, { status: "error", error: e instanceof Error ? e.message : "Image validation failed" }); } imageReplaceId.current = null; }
  function addVideo(file: File) { try { validate(file, VIDEO_FORMATS, VIDEO_MAX, "video"); video?.controller?.abort(); if (video?.previewUrl) URL.revokeObjectURL(video.previewUrl); const item: Item = { id: id(), kind: "video", file, previewUrl: URL.createObjectURL(file), status: "queued", progress: 0 }; setVideo(item); start(item, uploadVideo, p => setVideo(cur => cur ? { ...cur, ...p } : cur)); } catch (e) { toast(e instanceof Error ? e.message : "Video validation failed", "error"); } }
  function addAudio(file: File) { try { validate(file, AUDIO_FORMATS, AUDIO_MAX, "audio"); audio?.controller?.abort(); if (audio?.previewUrl) URL.revokeObjectURL(audio.previewUrl); const item: Item = { id: id(), kind: "audio", file, previewUrl: URL.createObjectURL(file), status: "queued", progress: 0 }; setAudio(item); start(item, uploadAudio, p => setAudio(cur => cur ? { ...cur, ...p } : cur)); } catch (e) { toast(e instanceof Error ? e.message : "Audio validation failed", "error"); } }
  function retry(item: Item) { if (item.kind === "image") start(item, uploadImage, p => setImage(item.id, p)); else if (item.kind === "video") start(item, uploadVideo, p => setVideo(cur => cur ? { ...cur, ...p } : cur)); else start(item, uploadAudio, p => setAudio(cur => cur ? { ...cur, ...p } : cur)); }
  function removeImage(target: string) { setImages(cur => { const item = cur.find(i => i.id === target); item?.controller?.abort(); if (item?.previewUrl) URL.revokeObjectURL(item.previewUrl); return cur.filter(i => i.id !== target); }); }
  function stopStream() { if (timer.current) window.clearInterval(timer.current); timer.current = null; stream.current?.getTracks().forEach(t => t.stop()); stream.current = null; recorder.current = null; }
  async function startRecording() { try { const media = await navigator.mediaDevices.getUserMedia({ audio: true }); stream.current = media; chunks.current = []; const rec = new MediaRecorder(media); recorder.current = rec; rec.ondataavailable = ev => ev.data.size && chunks.current.push(ev.data); rec.onstop = () => { const blob = new Blob(chunks.current, { type: rec.mimeType || "audio/webm" }); addAudio(new File([blob], `voice-${Date.now()}.webm`, { type: blob.type })); stopStream(); setRecording("idle"); setSeconds(0); }; rec.start(); setRecording("recording"); timer.current = window.setInterval(() => setSeconds(s => s + 1), 1000); } catch { toast("Microphone permission denied. Allow microphone and retry.", "error"); } }
  function pauseRecording() { recorder.current?.pause(); if (timer.current) window.clearInterval(timer.current); timer.current = null; setRecording("paused"); }
  function resumeRecording() { recorder.current?.resume(); timer.current = window.setInterval(() => setSeconds(s => s + 1), 1000); setRecording("recording"); }
  function stopRecording() { recorder.current?.stop(); if (timer.current) window.clearInterval(timer.current); timer.current = null; }
  function deleteRecording() { if (recorder.current && recorder.current.state !== "inactive") recorder.current.stop(); stopStream(); chunks.current = []; setRecording("idle"); setSeconds(0); }
  return <div className="grid gap-4"><input ref={imageRef} type="file" className="hidden" accept=".jpg,.jpeg,.png,.webp,.heic,image/*" multiple onChange={e => e.target.files && addImages(e.target.files)}/><input ref={imageReplaceRef} type="file" className="hidden" accept=".jpg,.jpeg,.png,.webp,.heic,image/*" onChange={e => replaceImage(e.target.files)}/><input ref={videoRef} type="file" className="hidden" accept=".mp4,.mov,.webm,.mkv,video/*" onChange={e => e.target.files?.[0] && addVideo(e.target.files[0])}/><input ref={audioRef} type="file" className="hidden" accept=".mp3,.wav,.m4a,.ogg,.aac,audio/*" onChange={e => e.target.files?.[0] && addAudio(e.target.files[0])}/><Section icon={<ImageIcon/>} title="Upload Image" desc="jpg, jpeg, png, webp, heic up to 10 MB" button="Upload Image" onClick={() => imageRef.current?.click()}><div onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); addImages(e.dataTransfer.files); }} className="rounded-2xl border border-dashed border-slate-300 p-5 text-center text-sm">Drag images here or browse files.</div><List items={images} onCancel={i => i.controller?.abort()} onRetry={retry} onRemove={i => removeImage(i.id)} onReplace={i => { imageReplaceId.current = i.id; imageReplaceRef.current?.click(); }}/></Section><Section icon={<Video/>} title="Upload Video" desc="mp4, mov, webm, mkv up to 5 MB" button="Upload Video" onClick={() => videoRef.current?.click()}>{video ? <List items={[video]} onCancel={i => i.controller?.abort()} onRetry={retry} onRemove={() => { video?.controller?.abort(); setVideo(undefined); }} onReplace={() => videoRef.current?.click()}/> : <Hint text="No video uploaded."/>}</Section><Section icon={<Mic/>} title="Record / Upload Voice" desc="mp3, wav, m4a, ogg, aac up to 10 MB" button="Upload Audio" onClick={() => audioRef.current?.click()}><div className="mb-3 rounded-2xl border p-3"><div className="flex flex-wrap items-center justify-between gap-3"><span className="font-black">Recording {String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</span><div className="flex gap-2">{recording === "idle" && <Btn onClick={startRecording}>Start</Btn>}{recording === "recording" && <Btn onClick={pauseRecording}><Pause size={14}/>Pause</Btn>}{recording === "paused" && <Btn onClick={resumeRecording}><Play size={14}/>Resume</Btn>}{recording !== "idle" && <><Btn onClick={stopRecording}><Square size={14}/>Stop</Btn><Btn onClick={deleteRecording}><Trash2 size={14}/>Delete</Btn></>}</div></div></div>{audio ? <List items={[audio]} onCancel={i => i.controller?.abort()} onRetry={retry} onRemove={() => { audio?.controller?.abort(); setAudio(undefined); }} onReplace={() => audioRef.current?.click()}/> : <Hint text="No voice uploaded or recorded."/>}</Section></div>;
}
function Section({ icon, title, desc, button, onClick, children }: { icon: React.ReactNode; title: string; desc: string; button: string; onClick: () => void; children: React.ReactNode }) { return <section className="rounded-[1.25rem] border border-slate-200/70 bg-white/50 p-4 backdrop-blur dark:border-white/10 dark:bg-white/[.04]"><div className="mb-3 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-teal-100 text-teal-700">{icon}</div><div><h3 className="font-black">{title}</h3><p className="text-xs text-slate-500">{desc}</p></div></div><button type="button" onClick={onClick} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-slate-950 px-4 py-2 text-sm font-black text-white dark:bg-white dark:text-slate-950"><Upload size={16}/>{button}</button></div>{children}</section>; }
function List({ items, onCancel, onRetry, onRemove, onReplace }: { items: Item[]; onCancel: (i: Item) => void; onRetry: (i: Item) => void; onRemove: (i: Item) => void; onReplace: (i: Item) => void }) { return <div className="mt-3 grid gap-3">{items.map(item => <div key={item.id} className="rounded-2xl border border-slate-200/70 bg-white/65 p-3"><div className="grid gap-3 md:grid-cols-[128px_1fr]"><Preview item={item}/><div><div className="flex justify-between gap-3"><div className="min-w-0"><p className="truncate font-black">{item.file.name}</p><p className="text-xs text-slate-500">{size(item.file.size)} · {item.status === "uploading" ? `Uploading ${item.progress}%` : item.status}</p>{item.error && <p className="mt-1 text-sm font-bold text-rose-600">{item.error}</p>}</div>{item.status === "success" ? <CheckCircle2 className="text-emerald-500"/> : item.status === "error" || item.status === "cancelled" ? <XCircle className="text-rose-500"/> : <RefreshCw className="animate-spin text-sky-500"/>}</div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-gradient-to-r from-teal-400 to-sky-500" style={{ width: `${item.progress}%` }}/></div><div className="mt-3 flex flex-wrap gap-2">{item.status === "uploading" && <Small onClick={() => onCancel(item)}>Cancel</Small>}{(item.status === "error" || item.status === "cancelled") && <Small onClick={() => onRetry(item)}>Retry</Small>}<Small onClick={() => onReplace(item)}>Replace</Small><Small onClick={() => onRemove(item)}>Remove</Small></div></div></div></div>)}</div>; }
function Preview({ item }: { item: Item }) { if (item.kind === "image") return <div className="h-32 overflow-hidden rounded-2xl bg-slate-100">{item.previewUrl && ext(item.file) !== "heic" ? <img src={item.previewUrl} alt={item.file.name} className="h-full w-full object-cover"/> : <ImageIcon className="m-auto mt-12 text-slate-400"/>}</div>; if (item.kind === "video") return <video src={item.previewUrl} controls className="h-32 w-full rounded-2xl bg-slate-100 object-cover"/>; return <div className="grid h-32 place-items-center rounded-2xl bg-slate-100 p-3"><FileAudio className="text-violet-500"/>{item.previewUrl && <audio src={item.previewUrl} controls className="w-full"/>}</div>; }
function Hint({ text }: { text: string }) { return <div className="rounded-2xl border border-dashed border-slate-300 p-5 text-center text-sm text-slate-500">{text}</div>; }
function Btn({ onClick, children }: { onClick: () => void; children: React.ReactNode }) { return <button type="button" onClick={onClick} className="inline-flex items-center gap-1 rounded-xl border px-3 py-2 text-sm font-black">{children}</button>; }
function Small({ onClick, children }: { onClick: () => void; children: React.ReactNode }) { return <button type="button" onClick={onClick} className="rounded-xl border px-3 py-2 text-xs font-black">{children}</button>; }
export const emptyMediaValue: MediaUploadValue = emptyValue;
