import Link from "next/link";
import type { ReactNode } from "react";
import { ArrowRight, Loader2 } from "lucide-react";
export function Brand() { return <Link href="/" className="group flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-gradient-to-br from-teal-300 via-sky-300 to-violet-300 text-base font-black text-slate-950 shadow-[0_16px_40px_rgba(45,212,191,.28)] transition group-hover:scale-105">E</span><span><span className="block text-sm font-bold leading-4 text-slate-950 dark:text-white">Expert Connect AI</span><span className="block text-xs text-slate-500 dark:text-slate-400">AI service command center</span></span></Link>; }
export function ButtonLink({ href, children, variant = "primary" }: { href: string; children: ReactNode; variant?: "primary" | "secondary" }) { return <Link href={href} className={variant === "primary" ? "inline-flex items-center gap-2 rounded-2xl bg-slate-950 px-5 py-3 text-sm font-bold text-white shadow-[0_18px_44px_rgba(15,23,42,.18)] transition hover:-translate-y-0.5 hover:bg-slate-800 dark:bg-white dark:text-slate-950" : "inline-flex items-center gap-2 rounded-2xl border border-slate-200/80 bg-white/70 px-5 py-3 text-sm font-bold text-slate-900 shadow-sm backdrop-blur transition hover:bg-white dark:border-white/10 dark:bg-white/8 dark:text-white"}>{children}<ArrowRight size={16}/></Link>; }
export function PageShell({ children }: { children: ReactNode }) { return <main className="app-grid relative min-h-screen overflow-hidden text-slate-950 dark:text-white"><div className="pointer-events-none fixed inset-0 -z-10"><div className="absolute left-[-10rem] top-[-8rem] h-96 w-96 rounded-full bg-teal-300/20 blur-3xl"/><div className="absolute right-[-10rem] top-12 h-96 w-96 rounded-full bg-sky-300/20 blur-3xl"/></div>{children}</main>; }
export function DashboardShell({ title, subtitle, children, action }: { title: string; subtitle: string; children: ReactNode; action?: ReactNode }) { return <PageShell><header className="sticky top-0 z-30 border-b border-slate-200/70 bg-white/68 backdrop-blur-2xl dark:border-white/10 dark:bg-slate-950/60"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 sm:px-6"><Brand/><div className="flex items-center gap-3">{action}</div></div></header><section className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><div className="mb-8"><p className="mb-3 inline-flex rounded-full border border-teal-400/25 bg-teal-400/10 px-3 py-1 text-xs font-bold uppercase text-teal-700 dark:text-teal-200">Live workspace</p><h1 className="text-3xl font-black tracking-tight sm:text-4xl">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600 dark:text-slate-400">{subtitle}</p></div>{children}</section></PageShell>; }
export function Card({ children, className = "" }: { children: ReactNode; className?: string }) { return <div className={`rounded-[1.35rem] border border-slate-200/70 bg-white/72 shadow-[0_22px_70px_rgba(15,23,42,.08)] backdrop-blur-xl dark:border-white/10 dark:bg-white/[.07] ${className}`}>{children}</div>; }
export function StatCard({ label, value, icon }: { label: string; value: ReactNode; icon: ReactNode }) { return <Card className="p-5"><div className="flex items-center justify-between gap-4"><div><p className="text-sm font-medium text-slate-500 dark:text-slate-400">{label}</p><p className="mt-2 text-3xl font-black tracking-tight">{value}</p></div><div className="grid h-12 w-12 place-items-center rounded-2xl bg-gradient-to-br from-teal-200 via-sky-200 to-violet-200 text-slate-950">{icon}</div></div></Card>; }
export function EmptyState({ title, text }: { title: string; text: string }) { return <div className="rounded-[1.35rem] border border-dashed border-slate-300/90 bg-white/45 p-8 text-center backdrop-blur dark:border-white/15 dark:bg-white/[.04]"><p className="font-bold">{title}</p><p className="mt-2 text-sm text-slate-500 dark:text-slate-400">{text}</p></div>; }
export function LoadingState({ label = "Loading" }: { label?: string }) { return <div className="flex items-center justify-center gap-2 rounded-[1.35rem] border border-slate-200/70 bg-white/70 p-8 text-sm text-slate-500 shadow-sm backdrop-blur dark:border-white/10 dark:bg-white/[.06] dark:text-slate-400"><Loader2 className="animate-spin text-teal-500" size={18}/>{label}</div>; }
export function StatusPill({ children, tone = "neutral" }: { children: ReactNode; tone?: "neutral" | "good" | "warn" | "danger" | "info" }) { const styles = { neutral:"bg-slate-100 text-slate-700 ring-slate-200 dark:bg-white/10 dark:text-slate-300 dark:ring-white/10", good:"bg-emerald-50 text-emerald-700 ring-emerald-200 dark:bg-emerald-400/10 dark:text-emerald-200", warn:"bg-amber-50 text-amber-700 ring-amber-200 dark:bg-amber-400/10 dark:text-amber-200", danger:"bg-rose-50 text-rose-700 ring-rose-200 dark:bg-rose-400/10 dark:text-rose-200", info:"bg-sky-50 text-sky-700 ring-sky-200 dark:bg-sky-400/10 dark:text-sky-200" }; return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold capitalize ring-1 ${styles[tone]}`}>{children}</span>; }
